#version: '3'
#
#services:
#  postgres:
#    image: postgres
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: "Hacizade22082022!"
#    ports:
#      - "5432:5432"
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
